/**
 * Replaces the `componentInfoContext` that `docs/src/utils` used to export.
 *
 * The original was generated by the gulp docgen pass over react-docgen, which
 * made the conformance tests depend on a docs build. Phase 0 deleted that app,
 * so this derives the same metadata by walking `src/` instead — see landmine 4
 * in PLAN.md. Nothing here may reach for `docs/`.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const srcDir = path.join(root, 'src')

// Directories holding public components. `src/lib` is support code and
// `lib`/`utils` subdirectories inside a component folder are implementation.
const COMPONENT_ROOTS = ['addons', 'collections', 'elements', 'modules', 'views']

const isComponentFile = (name) => /^[A-Z]\w*\.js$/.test(name)

/**
 * `Button.Group = ButtonGroup` in the parent module is the authoritative
 * statement of a child's public API path, so read it rather than guessing at
 * where the parent's name stops and the child's suffix starts.
 */
const readStatics = (file) => {
  const source = fs.readFileSync(file, 'utf8')
  const parent = path.basename(file, '.js')
  const statics = {}

  const pattern = new RegExp(`^${parent}\\.([A-Z]\\w*) = (\\w+)$`, 'gm')
  let match = pattern.exec(source)

  while (match !== null) {
    const [, subcomponentName, childName] = match
    statics[childName] = subcomponentName
    match = pattern.exec(source)
  }

  return statics
}

const byDisplayName = {}

for (const area of COMPONENT_ROOTS) {
  const areaDir = path.join(srcDir, area)

  for (const folder of fs.readdirSync(areaDir)) {
    const folderDir = path.join(areaDir, folder)
    if (!fs.statSync(folderDir).isDirectory()) continue

    const files = fs.readdirSync(folderDir).filter(isComponentFile)
    const parentFile = path.join(folderDir, `${folder}.js`)
    const statics = fs.existsSync(parentFile) ? readStatics(parentFile) : {}

    for (const file of files) {
      const displayName = path.basename(file, '.js')
      const isChild = displayName !== folder
      const subcomponentName = statics[displayName]

      byDisplayName[displayName] = {
        displayName,
        filenameWithoutExt: displayName,
        repoPath: `src/${area}/${folder}/${file}`,
        isChild,
        parentDisplayName: isChild ? folder : null,
        // A child that the parent never attaches has no path under its parent;
        // it is reachable only as a top-level export.
        apiPath: isChild && subcomponentName ? `${folder}.${subcomponentName}` : displayName,
      }
    }
  }
}

export const componentInfoContext = { byDisplayName }

export default componentInfoContext
