/**
 * Generates one Storybook CSF file per example section directory.
 *
 * `docs/src/examples` is laid out as `area/Component/Section/*Example*.js`,
 * which is Storybook's hierarchy with different punctuation:
 *
 *   docs/src/examples/elements/Button/Types/ButtonExampleEmphasis.js
 *     → title 'Elements/Button/Types', story 'Emphasis'
 *
 * The files are generated rather than globbed at run time on purpose: Chromatic's
 * TurboSnap decides what to re-snapshot by walking the builder's dependency
 * graph, and a run-time glob would tie every story to every example. See
 * "Phase 3" in PLAN.md.
 *
 * Run with `yarn stories`.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const examples = path.join(root, 'docs/src/examples')

const titleCase = (segment) => segment.charAt(0).toUpperCase() + segment.slice(1)

/**
 * Storybook humanises story names from their export names, but takes title
 * segments verbatim — so `GroupVariations` stays glued together in the sidebar
 * unless it is split here.
 */
const humanise = (segment) => titleCase(segment).replace(/([a-z])([A-Z])/g, '$1 $2')

/** `ButtonExampleEmphasis` → `Emphasis`; a bare `PaginationExample` → `Pagination`. */
const storyName = (filename) => {
  const match = /^(.*?)Example(.*)$/.exec(filename)
  if (!match) return filename

  return match[2] || match[1]
}

/** Export names must be identifiers, and unique within their file. */
const exportName = (name, taken) => {
  let candidate = name.replace(/[^A-Za-z0-9]/g, '')
  if (/^\d/.test(candidate)) candidate = `Story${candidate}`

  let unique = candidate
  for (let i = 2; taken.has(unique); i += 1) unique = `${candidate}${i}`
  taken.add(unique)

  return unique
}

const sections = []
for (const area of fs.readdirSync(examples)) {
  const areaPath = path.join(examples, area)
  if (!fs.statSync(areaPath).isDirectory()) continue

  for (const component of fs.readdirSync(areaPath)) {
    const componentPath = path.join(areaPath, component)
    if (!fs.statSync(componentPath).isDirectory()) continue

    for (const section of fs.readdirSync(componentPath)) {
      const sectionPath = path.join(componentPath, section)
      if (!fs.statSync(sectionPath).isDirectory()) continue

      sections.push({ area, component, section, sectionPath })
    }
  }
}

let written = 0
let stories = 0
let skipped = []

for (const { area, component, section, sectionPath } of sections) {
  const files = fs
    .readdirSync(sectionPath)
    .filter((f) => f.endsWith('.js') && f.includes('Example') && !f.endsWith('.stories.js'))
    .sort()

  // Random data and visual regression testing are incompatible: a faker string
  // differs on every run, so every snapshot would differ. These examples are
  // left out until they are rewritten with fixed data.
  const usable = files.filter((f) => {
    const source = fs.readFileSync(path.join(sectionPath, f), 'utf8')
    if (/from 'faker'/.test(source)) {
      skipped.push(`${area}/${component}/${section}/${f}`)
      return false
    }
    return true
  })

  if (usable.length === 0) continue

  const taken = new Set()
  const entries = usable.map((file) => {
    const base = file.replace(/\.js$/, '')
    return { base, export: exportName(storyName(base), taken) }
  })

  const title = `${titleCase(area)}/${component}/${humanise(section)}`
  const body = [
    '// Generated by scripts/generate-stories.mjs — run `yarn stories` to update.',
    "import React from 'react'",
    '',
    ...entries.map((e) => `import ${e.base} from './${e.base}'`),
    '',
    `export default { title: '${title}' }`,
    '',
    ...entries.map((e) => `export const ${e.export} = { render: () => <${e.base} /> }`),
    '',
  ].join('\n')

  fs.writeFileSync(path.join(sectionPath, `${section}.stories.js`), body)
  written += 1
  stories += entries.length
}

console.log(`wrote ${written} story files covering ${stories} stories`)
if (skipped.length) {
  console.log(`skipped ${skipped.length} examples that import faker:`)
  for (const s of skipped) console.log(`  ${s}`)
}
